apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 10.244.180.202/32
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: memory request for container
      image-clf-inf37; memory limit for container image-clf-inf37; memory request
      for init container prepare; memory limit for init container prepare'
    kubernetes.io/psp: nautilususerpolicy
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-01-07T04:02:15Z"
  generateName: image-clf-inf37-5b94d976d-
  labels:
    created-by: kubeless
    function: image-clf-inf37
    pod-template-hash: 5b94d976d
  name: image-clf-inf37-5b94d976d-kj69x
  namespace: racelab
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: image-clf-inf37-5b94d976d
    uid: 50a2d56b-d28c-479a-82e5-427fd902f393
  resourceVersion: "1071700717"
  selfLink: /api/v1/namespaces/racelab/pods/image-clf-inf37-5b94d976d-kj69x
  uid: 7a97e414-c706-4521-94dd-57e17bbf0b5c
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In
            values:
            - production
  containers:
  - env:
    - name: FUNC_HANDLER
      value: handler
    - name: MOD_NAME
      value: image-clf-inf37
    - name: FUNC_TIMEOUT
      value: "10800"
    - name: FUNC_RUNTIME
      value: gpupython3.7
    - name: FUNC_MEMORY_LIMIT
      value: "0"
    - name: FUNC_PORT
      value: "8080"
    - name: KUBELESS_INSTALL_VOLUME
      value: /kubeless
    - name: PYTHONPATH
      value: $(KUBELESS_INSTALL_VOLUME)/lib/python3.7/site-packages:$(KUBELESS_INSTALL_VOLUME)
    - name: NVIDIA_VISIBLE_DEVICES
      value: none
    image: gitlab-registry.nautilus.optiputer.net/prp/kubeless:latest
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 1
    name: image-clf-inf37
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        memory: 4Gi
      requests:
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /kubeless
      name: image-clf-inf37
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-f8rzs
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - echo '6efad1d0c192e2668d1d322a67742dd226d04619168c271024692be81fd06bfb  /src/image-clf-inf37.py'
      > /tmp/func.sha256 && sha256sum -c /tmp/func.sha256 && cp /src/image-clf-inf37.py
      /kubeless/image-clf-inf37.py && cp /src/requirements.txt /kubeless
    command:
    - sh
    - -c
    image: kubeless/unzip@sha256:f162c062973cca05459834de6ed14c039d45df8cdb76097f50b028a1621b3697
    imagePullPolicy: IfNotPresent
    name: prepare
    resources:
      limits:
        memory: 4Gi
      requests:
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /kubeless
      name: image-clf-inf37
    - mountPath: /src
      name: image-clf-inf37-deps
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-f8rzs
      readOnly: true
  nodeName: hcc-gpn-k8-1.unl.edu
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: nautilus.io/chase-ci
    operator: Exists
  volumes:
  - emptyDir: {}
    name: image-clf-inf37
  - configMap:
      defaultMode: 420
      name: image-clf-inf37
    name: image-clf-inf37-deps
  - name: default-token-f8rzs
    secret:
      defaultMode: 420
      secretName: default-token-f8rzs
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-01-07T04:02:17Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-01-07T04:02:18Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-01-07T04:02:18Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-01-07T04:02:15Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://c571f61c198ca997ca9300cbe6079f6c9b40db58d1906fc756eec2f14ba59fa2
    image: gitlab-registry.nautilus.optiputer.net/prp/kubeless:latest
    imageID: docker-pullable://gitlab-registry.nautilus.optiputer.net/prp/kubeless@sha256:57e0022f1cb57c057c3a1a38ee0e1b971c6e0f270ac9d7c4b73837ea4af5d9f1
    lastState: {}
    name: image-clf-inf37
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-01-07T04:02:18Z"
  hostIP: 129.93.241.2
  initContainerStatuses:
  - containerID: docker://447e6b5af0e13b43059d65b6050dee1b0b2c5849bc95a217d5504d903d7af578
    image: sha256:d2c5621fdfa3f219980e6d3149083b28b74e671ca8059fb1b7343750ae17b27d
    imageID: docker-pullable://kubeless/unzip@sha256:f162c062973cca05459834de6ed14c039d45df8cdb76097f50b028a1621b3697
    lastState: {}
    name: prepare
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://447e6b5af0e13b43059d65b6050dee1b0b2c5849bc95a217d5504d903d7af578
        exitCode: 0
        finishedAt: "2020-01-07T04:02:17Z"
        reason: Completed
        startedAt: "2020-01-07T04:02:17Z"
  phase: Running
  podIP: 10.244.180.202
  podIPs:
  - ip: 10.244.180.202
  qosClass: Burstable
  startTime: "2020-01-07T04:02:15Z"
