apiVersion: v1
kind: PersistentVolume
metadata:
  name: wtb-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/racelab"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wtb-pvc
spec:
  storageClassName: fast
  volumeName: wtb-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi