apiVersion: v1
kind: Pod
metadata:
  name: transfer-pod
spec:
  containers:
  - name: edge-container
    image: kubeless/function-image-builder:latest
    volumeMounts:
    - mountPath: /racelab
      name: wtb-pv
  volumes:
  - name: wtb-pv
    persistentVolumeClaim:
      claimName: wtb-pvc
  restartPolicy: Always